module.exports.auth = require('./lib/middleware/auth')
module.exports.cookies = require('./lib/middleware/cookies')
module.exports.errors = require('./lib/middleware/errors')
module.exports.json = require('./lib/middleware/json')
module.exports.services = require('./lib/middleware/services')
module.exports.static = require('./lib/middleware/static')
module.exports.urlencoded = require('./lib/middleware/urlencoded')
